# Generated by Django 5.0.4 on 2024-05-01 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('price_sale', models.BigIntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shopping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingGood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_sales.good')),
                ('shopping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_sales.shopping')),
            ],
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.RemoveField(
            model_name='food',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
        migrations.RemoveField(
            model_name='food',
            name='status',
        ),
        migrations.RemoveField(
            model_name='food',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_sales.food'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_sales.good'),
        ),
    ]
