# Generated by Django 5.0.4 on 2024-05-02 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sales', '0004_alter_good_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
