# Generated by Django 5.0.4 on 2024-05-02 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sales', '0005_shopping_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
