# Generated by Django 5.0.4 on 2024-05-02 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sales', '0006_alter_shopping_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='price_sale',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='status',
        ),
        migrations.CreateModel(
            name='SellingFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('price', models.BigIntegerField(default=0)),
                ('price_sale', models.BigIntegerField(default=0)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_sales.food')),
                ('selling', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_sales.selling')),
            ],
        ),
    ]
