# Generated by Django 5.0.4 on 2024-05-02 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sales', '0007_selling_remove_ingredient_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='good',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
