# Generated by Django 5.0.4 on 2024-05-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sales', '0008_food_status_alter_good_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingfood',
            old_name='price',
            new_name='good_price',
        ),
        migrations.RenameField(
            model_name='sellingfood',
            old_name='price_sale',
            new_name='good_price_sale',
        ),
        migrations.AddField(
            model_name='sellingfood',
            name='good_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sellingfood',
            name='total_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellingfood',
            name='total_price_sale',
            field=models.BigIntegerField(default=0),
        ),
    ]
