# Generated by Django 5.0.4 on 2024-05-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sales', '0009_rename_price_sellingfood_good_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellingfood',
            name='good_name',
            field=models.CharField(max_length=50),
        ),
    ]
