# Generated by Django 5.0.4 on 2024-05-02 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sales', '0010_alter_sellingfood_good_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellingFoodIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.BigIntegerField(default=0)),
                ('price_sale', models.BigIntegerField(default=0)),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_sales.good')),
                ('selling_food', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='food_sales.sellingfood')),
            ],
        ),
    ]
