# Generated by Django 5.0.4 on 2024-05-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_sales', '0012_remove_sellingfood_good_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.BigIntegerField(default=0)),
                ('unit', models.CharField(max_length=10)),
                ('amount', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=50)),
                ('store_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
